repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: "^vendor/"
      - id: end-of-file-fixer
        exclude: "^vendor/"
      - id: check-yaml
        exclude: '^mkdocs\.yml$'
      - id: check-added-large-files
        args: ["--maxkb=2000"]
        exclude: '\.(hdf5|h5|pt|pth)$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: "^vendor/"
      - id: ruff-format
        exclude: "^vendor/"

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
